name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    needs: [lint]
    uses: ./.github/workflows/build.yml

  deploy-pages:
    needs: [build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/deploy-web.yml
    secrets: inherit
