name: Deploy Web

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v6
        with:
          name: web-dist
          path: packages/web/dist
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy packages/web/dist --project-name=imposition
